# .github/workflows/ci.yml
name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate lockfile
        run: npm i --package-lock-only
      - uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]          # only current LTS + newest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: package-lock
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run test:coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node }}
          path: coverage/
          retention-days: 30

  lint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: package-lock
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npm run lint -- --format stylish > lint.txt
      - uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: lint.txt