name: Deploy Documentation

on:
  push:
    paths:
      - 'README.md'
      - 'docs/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docs
        run: |
          mkdir -p docs-build
          cp README.md docs-build/
          cat > docs-build/index.html << 'EOF'
          <!DOCTYPE html><html><head><title>Docs</title><meta charset="utf-8"><style>body{font-family:Arial;margin:40px auto;max-width:800px;line-height:1.6}</style></head><body><div id="content"></div><script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script><script>fetch('README.md').then(r=>r.text()).then(t=>document.getElementById('content').innerHTML=marked.parse(t))</script></body></html>
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-build
          destination_dir: docs